### ISSUE TITLE
Bundle not compliant with JMS/Serializer v2.0.0

### ISSUE THREAD

**Issue by picks44** [fre5h/VichUploaderSerializationBundle#11]
Do you plan to upgrade your bundle so that it can be used with the lastest JMS/Serializer version ?

**Comment by fre5h** [comment]
I will take a look what have changed in JMS/Serializer v2.0.0 and fix my bundle

**Comment by picks44** [comment]
That would be great! Thanks a lot!

**Comment by picks44** [comment]
@fre5h any news about this ? I've add the quick look at @jms/serializer 2.0 and apparently there are no big changes : https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/2.0.0

**Comment by fre5h** [comment]
@picks44 What exactly error do you have?

**Comment by picks44** [comment]
@fre5h when doing `php composer.phar require fresh/vich-uploader-serialization-bundle` I get 

```
Using version ^1.0 for fresh/vich-uploader-serialization-bundle

fresh/vich-uploader-serialization-bundle v1.0.9 requires jms/serializer-bundle ~1.1 -> satisfiable by jms/serializer-bundle[1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.5.0] but these conflict with your requirements or min
imum-stability.
```

**Comment by fre5h** [comment]
@picks44 
I have already tested bundle with version 2.0 of jms-serializer, it works, no changes needed. Fix is ready, I am just waiting for finishing CI task, it will take few minutes. Then I will create a new patch version of my bundle which will support jms-serializer 2.0

**Comment by picks44** [comment]
@fre5h you're the best ! thank you so much. I'll let you close the issue when it's ready ;)

**Comment by fre5h** [comment]
@picks44 Try this version `1.0.11` or if you use `~1.0` just run composer update

**Comment by picks44** [comment]
Install successfully completed! Now I'll test the bundle on my project. Thanks man!
