### ISSUE TITLE
Cannot autowire service

### ISSUE THREAD

**Issue by JoydS** [fre5h/VichUploaderSerializationBundle#20]
Hello,

I'm juste trying to update the dependance but I have this error with symfony 3.4 and I got this error :  

>  [RuntimeException]                                                               
>   An error occurred when executing the "'cache:clear --no-warmup'" command:        
>   In DefinitionErrorExceptionPass.php line 37:                                     
>                                                                                    
>     Cannot autowire service "Fresh\VichUploaderSerializationBundle\EventListene    
>     r\JmsSerializerSubscriber": argument "$storage" of method "__construct()" r    
>     eferences interface "Vich\UploaderBundle\Storage\StorageInterface" but no s    
>     uch service exists. You should maybe alias this interface to one of these e    
>     xisting services: "vich_uploader.storage.file_system", "meero.vich.gaufrett    
>     e_storage". Did you create a class that implements this interface?             

Do you have any idea what's going on ?

Thank you,

**Comment by alfupe** [comment]
Same error in a fresh install using Symfony 4.1. thx

**Comment by r3m4k3** [comment]
Any update?

**Comment by fre5h** [comment]
@r3m4k3 Please check `2.1.0` release. Should be fixed
