### ISSUE TITLE
Support Symfony LTS 4.4

### ISSUE THREAD

**Issue by aless673** [fre5h/VichUploaderSerializationBundle#35]
Hi,

v2.4.2 supports ^4.3
v3.0.0 supports ^5.0

Can't use your bundle with an LTS symfony 4.4 project !

**Comment by fre5h** [comment]
@aless673 Hi. You can use v2.4.3, I've just checked on own project, it is compatible with Symfony 4.4 LTS. 
Supports ^4.3 means any version since 4.3.0 till 5.0, in other words any minor version till the next major. So you can install it.
