### ISSUE TITLE
Serializing an entity manually does not work with the annotated fields.

### ISSUE THREAD

**Issue by Canser** [fre5h/VichUploaderSerializationBundle#36]
I am passing extra data (user info.) to lexic jwt authentication success response. Serializing the entity manually above:

`$serializer = new SerializerBuilder();`
`$data['user'] = $serializer->create()->build()->toArray($user);`

Manually serializing does not work. Do you know a solution? Or any other better way?

**Comment by fre5h** [comment]
What do you mean `Manually serializing does not work.`? Does not work at all? Or your user has file (VichUploadFile) field and it is not being serialized?

**Comment by fre5h** [comment]
@Canser Is it still actual?
