### ISSUE TITLE
composer req fresh/vich-uploader-serialization-bundle='~3.2' error

### ISSUE THREAD

**Issue by GiantVlad** [fre5h/VichUploaderSerializationBundle#48]
Create new empty composer project, and run:
```
composer req fresh/vich-uploader-serialization-bundle='~3.2' 
```
**Error:**
 Could not find package fresh/vich-uploader-serialization-bundle in a version matching "~3.2" and a stability matching "dev".

**Comment by fre5h** [comment]
@GiantVlad I've created the missing tag. Please try again
